import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; 

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { ClerkProvider } from "@clerk/nextjs";

const publishableKey = process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY!;

if (!publishableKey) {
  throw new Error('Missing Publishable Key. Please set EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY in your .env')
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create E-Commerce-App using Next.js",
  description: "Generated by Samim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider publishableKey={publishableKey}>
        <html lang="en">
      <body className={inter.className}>
        {children}
        </body>
    </html>
    </ClerkProvider>
   
  );
}
