import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"; 

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create E-Commerce-App using Next.js",
  description: "Generated by Samim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider publishableKey={process.env.EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY}>
        <html lang="en">
      <body className={inter.className}>
        <main>{children}</main>
        </body>
    </html>
    </ClerkProvider>
   
  );
}
